/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { forwardRef, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from 'three';

const Model = forwardRef(function Model(props, ref) {

    const { nodes, materials } = useGLTF("plane.glb");
    return (
        <group {...props} dispose={null} ref={ref}>
            <mesh
                geometry={nodes.body.geometry}

                position={[0, -0.25, 0]}
            >
                <meshStandardMaterial color={'salmon'} />
            </mesh>
            <mesh
                geometry={nodes.leftWing.geometry}
                position={[2.5, -0.25, 1]}
            >
                <meshStandardMaterial color={'orange'} />
            </mesh>
            <mesh
                geometry={nodes.rightWing.geometry}
                position={[-2.5, -0.25, 1]}
            >
                <meshStandardMaterial color={'orange'} />
            </mesh>
            <mesh
                geometry={nodes.leftStable.geometry}
                position={[1.1, -0.25, -3.25]}
            >
                <meshStandardMaterial color={'yellow'} />
            </mesh>
            <mesh
                geometry={nodes.rightStable.geometry}
                position={[-1.1, -0.25, -3.25]}
            >
                <meshStandardMaterial color={'yellow'} />
            </mesh>
            <mesh
                geometry={nodes.rudder.geometry}
                position={[0, 0.9, -3.35]}
                rotation={[0, 0, -Math.PI / 2]}
            >
                <meshStandardMaterial color={'yellow'} />
            </mesh>
        </group>
    );
});
useGLTF.preload("plane.glb");
export default Model;
